package dev.verbum.i18n;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Keyword localization for Verbum.
 *
 * Verbum's grammar is keyword-first: every line starts with a structural word
 * ("when", "every", "if", ...) or an action verb ("give", "kill", "set", ...).
 * This class maps the first word of a line from the active language into the
 * canonical English keyword the interpreter already understands. Words that are
 * not keywords (player names, item names, messages) are never rewritten, so the
 * body of a line stays in whatever language the author writes it in.
 *
 * The default language is English, where every word maps to itself.
 */
public final class KeywordResolver {

    /** code (ISO 639-1) -> native name */
    private static final Map<String, String> LANGUAGES = new LinkedHashMap<>();
    /** code -> foreign keyword -> canonical English keyword */
    private static final Map<String, Map<String, String>> TABLES = new LinkedHashMap<>();
    /** code -> native name -> same code, for the "language" directive */
    private static final Map<String, String> BY_NATIVE = new LinkedHashMap<>();

    private final Map<String, String> table;
    private final String code;

    private KeywordResolver(String code, Map<String, String> table) {
        this.code = code;
        this.table = table;
    }

    /** English: identity mapping, never fails. */
    public static final KeywordResolver ENGLISH = new KeywordResolver("en", Map.of());

    /** Returns the resolver for a language code ("en", "es", "de", ...). Unknown codes fall back to English. */
    public static KeywordResolver forCode(String code) {
        if (code == null) return ENGLISH;
        Map<String, String> t = TABLES.get(code.toLowerCase());
        return t == null ? ENGLISH : new KeywordResolver(code.toLowerCase(), t);
    }

    /** Resolves a language by its native name too: "spanish", "español" -> es. */
    public static KeywordResolver forName(String name) {
        if (name == null) return ENGLISH;
        String code = BY_NATIVE.get(name.trim().toLowerCase());
        return code == null ? ENGLISH : forCode(code);
    }

    /** Canonical English keyword for a foreign first-word; returns the word itself if unknown. */
    public String resolve(String word) {
        if (word == null) return word;
        String low = word.toLowerCase();
        String c = table.get(low);
        return c != null ? c : low;
    }

    public String code() { return code; }

    /** All supported language codes. */
    public static java.util.Set<String> codes() { return LANGUAGES.keySet(); }

    public static String nativeName(String code) {
        return LANGUAGES.getOrDefault(code.toLowerCase(), "English");
    }

    // ---------------------------------------------------------------- data

    static {
        // Each row:  ISO code, native name, then "foreign=english;foreign=english;..."
        // Single-word keywords only, so first-word normalization is safe.
        String[][] data = {
            // --- Germanic / North & West Europe ---------------------------
            {"en", "English", "when=when;every=every;on=on;if=if;unless=unless;else=else;repeat=repeat;for=for;until=until;return=return;action=action;function=function;command=command;menu=menu;give=give;take=take;kill=kill;damage=damage;heal=heal;teleport=teleport;spawn=spawn;set=set;add=add;remove=remove;tell=tell;announce=announce;create=create;delete=delete;save=save;load=load;call=call;wait=wait;cooldown=cooldown;fly=fly;feed=feed;freeze=freeze;ignite=ignite;explode=explode;ban=ban;kick=kick;clear=clear;close=close;open=open;drop=drop;enchant=enchant;equip=equip"},
            {"de", "Deutsch", "wenn=when;jede=every;auf=on;wenn=if;es sei denn=unless;sonst=else;wiederhole=repeat;für=for;bis=until;zurück=return;aktion=action;funktion=function;befehl=command;menü=menu;gib=give;nimm=take;töte=kill;schaden=damage;heile=heal;teleportiere=teleport;spawne=spawn;setze=set;füge hinzu=add;entferne=remove;sag=tell;verkünde=announce;erschaffe=create;lösche=delete;speichere=save;lade=load;rufe=call;warte=wait;abklingzeit=cooldown;fliege=fly;füttere=feed;friere=freeze;entzünde=ignite;explodiere=explode;verbanne=ban;trete=kick;leere=clear;schließe=close;öffne=open;fallen lassen=drop;verzaubere=enchant;rüste aus=equip"},
            {"nl", "Nederlands", "wanneer=when;elke=every;op=on;als=if;tenzij=unless;anders=else;herhaal=repeat;voor=for;tot=until;terug=return;actie=action;functie=function;commando=command;menu=menu;geef=give;neem=take;dood=kill;schade=damage;genees=heal;teleporteer=teleport;spawn=spawn;zet=set;voeg toe=add;verwijder=remove;vertel=tell;kondig aan=announce;maak=create;verwijder=delete;bewaar=save;laad=load;roep=call;wacht=wait;cooldown=cooldown;vlieg=fly;voer=feed;bevries=freeze;steek aan=ignite;explodeer=explode;verban=ban;schop=kick;leeg=clear;sluit=close;open=open;laat vallen=drop;betover=enchant;rust uit=equip"},
            {"da", "Dansk", "når=when;hver=every;på=on;hvis=if;medmindre=unless;ellers=else;gentag=repeat;for=for;indtil=until;returner=return;handling=action;funktion=function;kommando=command;menu=menu;giv=give;tag=take;dræb=kill;skade=damage;hel=heal;teleporter=teleport;spawn=spawn;sæt=set;tilføj=add;fjern=remove;fortæl=tell;bekendtgør=announce;skab=create;slet=delete;gem=save;indlæs=load;kald=call;vent=wait;nedkøling=cooldown;flyv=fly;fodr=feed;frys=freeze;antænd=ignite;eksploder=explode;forvis=ban;spark=kick;tøm=clear;luk=close;åbn=open;slipp=drop;fortryl=enchant;udstyr=equip"},
            {"sv", "Svenska", "när=when;varje=every;på=on;om=if;om inte=unless;annars=else;upprepa=repeat;för=for;tills=until;returnera=return;aktion=action;funktion=function;kommando=command;meny=menu;ge=give;ta=take;döda=kill;skada=damage;bota=heal;teleportera=teleport;spawna=spawn;sätt=set;lägg till=add;ta bort=remove;berätta=tell;tillkännage=announce;skapa=create;radera=delete;spara=save;ladda=load;ropa=call;vänta=wait;nedkylning=cooldown;flyg=fly;mata=feed;frys=freeze;tänd=ignite;explodera=explode;banna=ban;sparka=kick;töm=clear;stäng=close;öppna=open;släpp=drop;förtrolla=enchant;utrusta=equip"},
            {"no", "Norsk", "når=when;hver=every;på=on;hvis=if;med mindre=unless;ellers=else;gjenta=repeat;for=for;til=until;returner=return;handling=action;funksjon=function;kommando=command;meny=menu;gi=give;ta=take;drep=kill;skade=damage;hel=heal;teleporter=teleport;spawn=spawn;sett=set;legg til=add;fjern=remove;fortell=tell;kunngjør=announce;lag=create;slett=delete;lagre=save;last=load;rop=call;vent=wait;nedkjøling=cooldown;fly=fly;mata=feed;frys=freeze;tenn=ignite;eksploder=explode;forvis=ban;spark=kick;tøm=clear;lukk=close;åpne=open;slipp=drop;fortryl=enchant;utstyr=equip"},
            {"is", "Íslenska", "þegar=when;sérhver=every;á=on;ef=if;nema=unless;annars=else;endurtaktu=repeat;fyrir=for;þar til=until;skilaðu=return;aðgerð=action;fall=function;skipun=command;valmynd=menu;gefðu=give;tak=take;drep=kill;skaða=damage;græddu=heal;hreyfðu=teleport;spawna=spawn;stilltu=set;bættu við=add;fjarlægðu=remove;segðu=tell;tilkynntu=announce;búðu til=create;eyddu=delete;vistaðu=save;hlaððu=load;kallaðu=call;bíddu=wait;kæling=cooldown;fljúgðu=fly;fóðraðu=feed;frjósu=freeze;kveiktu=ignite;sprængdu=explode;bannaðu=ban;sparkaðu=kick;tæmdu=clear;lokaðu=close;opnaðu=open;láttu falla=drop;galdraðu=enchant;búnaðu=equip"},
            {"et", "Eesti", "kui=when;iga=every;edasi=on;kui=if;välja arvatud=unless;muidu=else;korda=repeat;jaoks=for;kuni=until;tagasta=return;tegevus=action;funktsioon=function;käsk=command;menüü=menu;anna=give;võta=take;tapa=kill;kahjusta=damage;ravi=heal;telepordi=teleport;spawni=spawn;sea=set;lisa=add;eemalda=remove;ütle=tell;teata=announce;loo=create;kustuta=delete;salvesta=save;laadi=load;kutsu=call;oota=wait;taastumine=cooldown;lenda=fly;toida=feed;külmuta=freeze;süüta=ignite;plahvata=explode;banni=ban;viska=kick;tühjenda=clear;sulge=close;avage=open;lase kukkuda=drop;loitsu=enchant;varusta=equip"},
            {"lv", "Latviešu", "kad=when;ikviens=every;uz=on;ja=if;ja vien=unless;citādi=else;atkārto=repeat;par=for;līdz=until;atgriez=return;darbība=action;funkcija=function;komanda=command;izvēlne=menu;iedod=give;paņem=take;nokauj=kill;bojā=damage;dziedē=heal;teleportē=teleport;spawno=spawn;uzstādi=set;pievieno=add;noņem=remove;pasaki=tell;paziņo=announce;izveido=create;izdzēs=delete;saglabā=save;ielādē=load;izsauc=call;gaidi=wait;atdzišana=cooldown;lido=fly;pabaro=feed;sasaldē=freeze;aizdedzini=ignite;eksplodē=explode;banno=ban;sper=kick;notīri=clear;aizver=close;atver=open;nomet=drop;apbur=enchant;aprīko=equip"},
            {"lt", "Lietuvių", "kai=when;kiekvieną=every;ant=on;jei=if;nebent=unless;kitaip=else;kartok=repeat;skirta=for;iki=until;grąžink=return;veiksmas=action;funkcija=function;komanda=command;meniu=menu;duok=give;paimk=take;nužudyk=kill;žalok=damage;išgydyk=heal;teleportuok=teleport;spawnink=spawn;nustatyk=set;pridėk=add;pašalink=remove;pasakyk=tell;paskelbk=announce;sukurk=create;ištrink=delete;išsaugok=save;įkelk=load;iškviesk=call;palauk=wait;atvėsimas=cooldown;skrisk=fly;pašerk=feed;užšaldyk=freeze;uždek=ignite;sprogk=explode;uždrausk=ban;spirk=kick;išvalyk=clear;uždaryk=close;atidaryk=open;pamesk=drop;apkerėk=enchant;aprūpink=equip"},
            {"fi", "Suomi", "kun=when;joka=every;päällä=on;jos=if;ellei=unless;muuten=else;toista=repeat;for=for;kunnes=until;palaa=return;toiminto=action;funktio=function;komento=command;valikko=menu;anna=give;ota=take;tapa=kill;vahingoita=damage;paranna=heal;teleporttaa=teleport;spawnaa=spawn;aseta=set;lisää=add;poista=remove;kerro=tell;ilmoita=announce;luo=create;poista=delete;tallenna=save;lataa=load;kutsu=call;odota=wait;viilennys=cooldown;lennä=fly;ruoki=feed;jäädytä=freeze;sytytä=ignite;räjähdä=explode;bannaa=ban;potkaise=kick;tyhjennä=clear;sulje=close;avaa=open;tiputa=drop;lumoa=enchant;varusta=equip"},
            // --- Romance / South & West Europe -----------------------------
            {"fr", "Français", "quand=when;chaque=every;sur=on;si=if;sauf si=unless;sinon=else;répète=repeat;pour=for;jusqu'à=until;retourne=return;action=action;fonction=function;commande=command;menu=menu;donne=give;prends=take;tue=kill;blesse=damage;soigne=heal;téléporte=teleport;apparais=spawn;mets=set;ajoute=add;retire=remove;dis=tell;annonce=announce;crée=create;supprime=delete;enregistre=save;charge=load;appelle=call;attends=wait;recharge=cooldown;vole=fly;nourris=feed;gèle=freeze;enflamme=ignite;explose=explode;bannis=ban;expulse=kick;vide=clear;ferme=close;ouvre=open;lâche=drop;enchant=enchant;équipe=equip"},
            {"es", "Español", "cuando=when;cada=every;en=on;si=if;a menos que=unless;sino=else;repite=repeat;para=for;hasta=until;devuelve=return;acción=action;función=function;comando=command;menú=menu;da=give;toma=take;mata=kill;daña=damage;cura=heal;teletransporta=teleport;genera=spawn;pon=set;añade=add;quita=remove;dile=tell;anuncia=announce;crea=create;borra=delete;guarda=save;carga=load;llama=call;espera=wait;enfriamiento=cooldown;vuela=fly;alimenta=feed;congela=freeze;enciende=ignite;explota=explode;banea=ban;expulsa=kick;limpia=clear;cierra=close;abre=open;deja caer=drop;encanta=enchant;equipa=equip"},
            {"pt", "Português", "quando=when;cada=every;em=on;se=if;a menos que=unless;senão=else;repete=repeat;para=for;até=until;retorna=return;ação=action;função=function;comando=command;menu=menu;dá=give;pega=take;mata=kill;dano=damage;cura=heal;teletransporta=teleport;gera=spawn;define=set;adiciona=add;remove=remove;diz=tell;anuncia=announce;cria=create;apaga=delete;salva=save;carrega=load;chama=call;espera=wait;recarga=cooldown;voa=fly;alimenta=feed;congela=freeze;incendeia=ignite;explode=explode;bane=ban;expulsa=kick;limpa=clear;fecha=close;abre=open;solta=drop;encanta=enchant;equipa=equip"},
            {"it", "Italiano", "quando=when;ogni=every;su=on;se=if;a meno che=unless;altrimenti=else;ripeti=repeat;per=for;fino a=until;ritorna=return;azione=action;funzione=function;comando=command;menu=menu;dai=give;prendi=take;uccidi=kill;danneggia=damage;cura=heal;teletrasporta=teleport;genera=spawn;imposta=set;aggiungi=add;rimuovi=remove;di=tell;annuncia=announce;crea=create;elimina=delete;salva=save;carica=load;chiama=call;aspetta=wait;ricarica=cooldown;vola=fly;nutri=feed;congela=freeze;incendia=ignite;esplodi=explode;bandisci=ban;espelli=kick;svuota=clear;chiudi=close;apri=open;lascia cadere=drop;incanta=enchant;equipaggia=equip"},
            {"ro", "Română", "când=when;fiecare=every;pe=on;dacă=if;dacă nu=unless;altfel=else;repetă=repeat;pentru=for;până=until;întoarce=return;acțiune=action;funcție=function;comandă=command;meniu=menu;dă=give;ia=take;omoară=kill;avariază=damage;vindecă=heal;teleportează=teleport;generează=spawn;setează=set;adaugă=add;elimină=remove;spune=tell;anunță=announce;creează=create;șterge=delete;salvează=save;încarcă=load;cheamă=call;așteaptă=wait;răcire=cooldown;zboară=fly;hrănește=feed;îngheață=freeze;incendiază=ignite;explodează=explode;bănuiește=ban;expulzează=kick;golește=clear;închide=close;deschide=open;lasă să cadă=drop;vrăjește=enchant;echipează=equip"},
            {"ca", "Català", "quan=when;cada=every;sobre=on;si=if;llevat que=unless;sinó=else;repeteix=repeat;per a=for;fins a=until;retorna=return;acció=action;funció=function;ordre=command;menú=menu;dona=give;pren=take;mata=kill;dany=damage;cura=heal;teletransporta=teleport;genera=spawn;estableix=set;afegeix=add;treu=remove;digues=tell;anuncia=announce;crea=create;esborra=delete;desa=save;carrega=load;crida=call;espera=wait;refredament=cooldown;vola=fly;alimenta=feed;congela=freeze;encén=ignite;explota=explode;bandeja=ban;expulsa=kick;neteja=clear;tanca=close;obre=open;deixa caure=drop;encanta=enchant;equipa=equip"},
            {"gl", "Galego", "cando=when;cada=every;en=on;se=if;a non ser que=unless;senón=else;repite=repeat;para=for;ata=until;devolve=return;acción=action;función=function;comando=command;menú=menu;dá=give;colla=take;mata=kill;danos=damage;cura=heal;teletransporta=teleport;xera=spawn;define=set;engade=add;quita=remove;dille=tell;anuncia=announce;crea=create;borra=delete;garda=save;carga=load;chama=call;espera=wait;refrixeración=cooldown;voa=fly;alimenta=feed;conxela=freeze;prende=ignite;explota=explode;banea=ban;expulsa=kick;limpia=clear;pecha=close;abre=open;deixa caer=drop;encanta=enchant;equipa=equip"},
            {"eu", "Euskara", "noiz=when;bakoitzean=every;gainean=on;baldin=if;ez bada=unless;bestela=else;errepikatu=repeat;for=for;arte=until;itzuli=return;ekintza=action;funtzioa=function;komandoa=command;menua=menu;eman=give;hartu=take;hil=kill;kaltetu=damage;sendatu=heal;teleportatu=teleport;sortu=spawn;ezarri=set;gehitu=add;kendu=remove;esan=tell;iragarri=announce;sorrarazi=create;ezabatu=delete;gorde=save;kargatu=load;deitu=call;itxaron=wait;hozte=cooldown;hegan=fly;elikatu=feed;izoztu=freeze;piztu=ignite;lehertu=explode;debakatu=ban;ostikatu=kick;garbitu=clear;itxi=close;ireki=open;bota=drop;xarmatu=enchant;hornitu=equip"},
            {"tr", "Türkçe", "ne zaman=when;her=every;üzerinde=on;eğer=if;olmadıkça=unless;aksi halde=else;tekrarla=repeat;için=for;kadar=until;geri dön=return;işlem=action;işlev=function;komut=command;menü=menu;ver=give;al=take;öldür=kill;hasar ver=damage;iyileştir=heal;ışınla=teleport;oluştur=spawn;ayarla=set;ekle=add;kaldır=remove;söyle=tell;duyur=announce;yarat=create;sil=delete;kaydet=save;yükle=load;çağır=call;bekle=wait;soğuma=cooldown;uç=fly;besle=feed;dondur=freeze;tutuştur=ignite;patlat=explode;yasakla=ban;at=kick;temizle=clear;kapat=close;aç=open;bırak=drop;büyüle=enchant;donat=equip"},
            {"az", "Azərbaycan", "nə vaxt=when;hər=every;üzərində=on;əgər=if;olmasa=unless;əks halda=else;təkrar et=repeat;üçün=for;qədər=until;qaytar=return;hərəkət=action;funksiya=function;əmrin=command;menyu=menu;ver=give;götür=take;öldür=kill;zərər ver=damage;sağalt=heal;teleport et=teleport;yarat=spawn;təyin et=set;əlavə et=add;çıxar=remove;de=tell;elan et=announce;yarat=create;sil=delete;yadda saxla=save;yüklə=load;çağır=call;gözlə=wait;soyutma=cooldown;uç=fly;bəslə=feed;dondur=freeze;yandır=ignite;partlat=explode;qadağan et=ban;vur=kick;təmizlə=clear;bağla=close;aç=open;at=drop;sehrlə=enchant;təchiz et=equip"},
            // --- Slavic / Central & East Europe ----------------------------
            {"pl", "Polski", "kiedy=when;każdy=every;na=on;jeśli=if;chyba że=unless;inaczej=else;powtórz=repeat;dla=for;dopóki=until;zwróć=return;akcja=action;funkcja=function;komenda=command;menu=menu;daj=give;weź=take;zabij=kill;zrań=damage;ulecz=heal;teleportuj=teleport;spawnuj=spawn;ustaw=set;dodaj=add;usuń=remove;powiedz=tell;ogłoś=announce;utwórz=create;usuń=delete;zapisz=save;wczytaj=load;wołaj=call;czekaj=wait;schłodzenie=cooldown;leć=fly;nakarm=feed;zamroź=freeze;podpal=ignite;eksploduj=explode;zbanuj=ban;wyrzuć=kick;wyczyść=clear;zamknij=close;otwórz=open;upuść=drop;zaczaruj=enchant;wyposaż=equip"},
            {"cs", "Čeština", "když=when;každý=every;na=on;pokud=if;pokud ne=unless;jinak=else;opakuj=repeat;pro=for;dokud=until;vrátit=return;akce=action;funkce=function;příkaz=command;menu=menu;dej=give;vezmi=take;zabij=kill;zraň=damage;vyléč=heal;teleportuj=teleport;spawnuj=spawn;nastav=set;přidej=add;odeber=remove;řekni=tell;oznam=announce;vytvoř=create;smaž=delete;ulož=save;načti=load;zavolej=call;počkej=wait;ochlazení=cooldown;leť=fly;nakrm=feed;zmraz=freeze;zapal=ignite;vybuchni=explode;zabanuj=ban;vykopni=kick;vyčisti=clear;zavři=close;otevři=open;pusť=drop;očaruj=enchant;vybav=equip"},
            {"sk", "Slovenčina", "keď=when;každý=every;na=on;ak=if;pokiaľ nie=unless;inak=else;opakuj=repeat;pre=for;až kým=until;vráť=return;akcia=action;funkcia=function;príkaz=command;menu=menu;daj=give;vezmi=take;zabi=kill;zraň=damage;vylieč=heal;teleportuj=teleport;spawnuj=spawn;nastav=set;pridaj=add;odober=remove;povedz=tell;oznám=announce;vytvor=create;zmaž=delete;ulož=save;načítaj=load;zavolaj=call;počkaj=wait;ochladenie=cooldown;leť=fly;nakŕm=feed;zmraz=freeze;zapáľ=ignite;vybuchni=explode;zabanuj=ban;vykopni=kick;vyčisti=clear;zatvor=close;otvor=open;pusť=drop;očaruj=enchant;vybav=equip"},
            {"sl", "Slovenščina", "ko=when;vsak=every;na=on;če=if;razen če=unless;sicer=else;ponovi=repeat;za=for;do=until;vrni=return;akcija=action;funkcija=function;ukaz=command;meni=menu;daj=give;vzemi=take;ubij=kill;poškoduj=damage;ozdravi=heal;teleportiraj=teleport;spawnaj=spawn;nastavi=set;dodaj=add;odstrani=remove;povej=tell;naznani=announce;ustvari=create;izbriši=delete;shrani=save;naloži=load;pokliči=call;počakaj=wait;ohlajevanje=cooldown;leti=fly;nahrani=feed;zamrzni=freeze;prižgi=ignite;eksplodiraj=explode;bannaj=ban;brcni=kick;izprazni=clear;zapri=close;odpri=open;spusti=drop;zacaraj=enchant;opremi=equip"},
            {"hr", "Hrvatski", "kada=when;svaki=every;na=on;ako=if;osim ako=unless;inače=else;ponovi=repeat;za=for;dok=until;vrati=return;radnja=action;funkcija=function;naredba=command;izbornik=menu;daj=give;uzmi=take;ubij=kill;ošteti=damage;izliječi=heal;teleportiraj=teleport;spawnaj=spawn;postavi=set;dodaj=add;ukloni=remove;reci=tell;objavi=announce;stvori=create;obriši=delete;spremi=save;učitaj=load;pozovi=call;čekaj=wait;hladnjenje=cooldown;leti=fly;nahrani=feed;zamrzni=freeze;zapali=ignite;eksplodiraj=explode;zabrani=ban;izbaci=kick;očisti=clear;zatvori=close;otvori=open;ispusti=drop;začaraj=enchant;opremi=equip"},
            {"bs", "Bosanski", "kada=when;svaki=every;na=on;ako=if;osim ako=unless;inače=else;ponovi=repeat;za=for;dok=until;vrati=return;radnja=action;funkcija=function;naredba=command;meni=menu;daj=give;uzmi=take;ubij=kill;ošteti=damage;izliječi=heal;teleportiraj=teleport;spawnaj=spawn;postavi=set;dodaj=add;ukloni=remove;reci=tell;objavi=announce;stvori=create;obriši=delete;spremi=save;učitaj=load;pozovi=call;čekaj=wait;hlađenje=cooldown;leti=fly;nahrani=feed;zamrzni=freeze;zapali=ignite;eksplodiraj=explode;zabrani=ban;izbaci=kick;očisti=clear;zatvori=close;otvori=open;ispusti=drop;začaraj=enchant;opremi=equip"},
            {"sr", "Српски", "када=when;сваки=every;на=on;ако=if;осим ако=unless;иначе=else;понављај=repeat;за=for;док=until;врати=return;радња=action;функција=function;команда=command;мени=menu;дај=give;узми=take;убиј=kill;оштети=damage;излечи=heal;телепортуј=teleport;спаунуј=spawn;постави=set;додај=add;уклони=remove;реци=tell;објави=announce;створи=create;обриши=delete;сачувај=save;учитај=load;позови=call;чекај=wait;хлађење=cooldown;лети=fly;нахрани=feed;замрзни=freeze;запали=ignite;експлодирај=explode;забрани=ban;избаци=kick;очисти=clear;затвори=close;отвори=open;испусти=drop;очарај=enchant;опреми=equip"},
            {"mk", "Македонски", "кога=when;секој=every;на=on;ако=if;освен ако=unless;инаку=else;повтори=repeat;за=for;додека=until;врати=return;акција=action;функција=function;команда=command;мени=menu;дај=give;земи=take;убиј=kill;оштети=damage;излечи=heal;телепортирај=teleport;спаунирај=spawn;постави=set;додај=add;отстрани=remove;кажи=tell;објави=announce;создај=create;избриши=delete;зачувај=save;вчитај=load;повикај=call;чекај=wait;ладење=cooldown;лети=fly;нахрани=feed;замрзни=freeze;запали=ignite;експлодирај=explode;забрани=ban;исфрли=kick;исчисти=clear;затвори=close;отвори=open;испушти=drop;намаѓија=enchant;опреми=equip"},
            {"bg", "Български", "когато=when;всеки=every;на=on;ако=if;освен ако=unless;иначе=else;повтори=repeat;за=for;докато=until;върни=return;действие=action;функция=function;команда=command;меню=menu;дай=give;вземи=take;убий=kill;нарани=damage;излекувай=heal;телепортирай=teleport;спавни=spawn;задай=set;добави=add;премахни=remove;кажи=tell;обяви=announce;създай=create;изтрий=delete;запази=save;зареди=load;извикай=call;изчакай=wait;охлаждане=cooldown;лети=fly;нахрани=feed;замрази=freeze;подпали=ignite;експлодирай=explode;забрани=ban;изрита=kick;изчисти=clear;затвори=close;отвори=open;пусни=drop;омагьосай=enchant;екипирай=equip"},
            {"ru", "Русский", "когда=when;каждый=every;на=on;если=if;если не=unless;иначе=else;повтори=repeat;для=for;пока=until;верни=return;действие=action;функция=function;команда=command;меню=menu;дай=give;возьми=take;убей=kill;повреди=damage;вылечи=heal;телепортируй=teleport;вызови=spawn;установи=set;добавь=add;удали=remove;скажи=tell;объяви=announce;создай=create;удали=delete;сохрани=save;загрузи=load;вызови=call;подожди=wait;перезарядка=cooldown;лети=fly;накорми=feed;заморозь=freeze;подожги=ignite;взорви=explode;запрети=ban;выкинь=kick;очисти=clear;закрой=close;открой=open;брось=drop;зачаруй=enchant;снаряди=equip"},
            {"uk", "Українська", "коли=when;кожен=every;на=on;якщо=if;якщо не=unless;інакше=else;повтори=repeat;для=for;до=until;поверни=return;дія=action;функція=function;команда=command;меню=menu;дай=give;візьми=take;убей=kill;пошкодь=damage;вилікуй=heal;телепортуй=teleport;спавни=spawn;встанови=set;додай=add;прибери=remove;скажи=tell;оголоси=announce;створи=create;видали=delete;збережи=save;завантаж=load;виклич=call;почекай=wait;перезарядка=cooldown;лети=fly;нагодуй=feed;заморозь=freeze;підпали=ignite;вибухни=explode;заборони=ban;викинь=kick;очисти=clear;закрий=close;відкрий=open;кинь=drop;зачаруй=enchant;споряди=equip"},
            {"be", "Беларуская", "калі=when;кожны=every;на=on;калі=if;калі не=unless;інакш=else;паўтары=repeat;для=for;пакуль=until;вярні=return;дзеянне=action;функцыя=function;каманда=command;меню=menu;дай=give;вазьмі=take;забі=kill;пашкодзь=damage;вылечы=heal;тэлепартуй=teleport;спаўні=spawn;устанаві=set;дадай=add;прыбяры=remove;скажы=tell;абвясці=announce;ствары=create;выдалі=delete;захавай=save;загрузі=load;выкліч=call;пачакай=wait;перазарадка=cooldown;ляці=fly;накармі=feed;замарозь=freeze;падпалі=ignite;выбухні=explode;забарані=ban;выкінь=kick;ачысці=clear;зачыні=close;адчыні=open;кінь=drop;зачаруй=enchant;спарадзі=equip"},
            {"sq", "Shqip", "kur=when;çdo=every;në=on;nëse=if;në mos qoftë se=unless;përndryshe=else;përsërit=repeat;për=for;deri=until;kthe=return;veprim=action;funksion=function;komandë=command;menu=menu;jep=give;merr=take;vris=kill;dëmto=damage;shëro=heal;teleporto=teleport;spawno=spawn;cakto=set;shto=add;hiq=remove;thuaj=tell;njofto=announce;krijo=create;fshi=delete;ruaj=save;ngarko=load;thirr=call;prit=wait;ftohje=cooldown;fluturo=fly;ushqe=feed;ngri=freeze;ndiz=ignite;shpërthe=explode;bano=ban;dëbo=kick;pastro=clear;mbyll=close;hap=open;lësho=drop;magjep=enchant;pajis=equip"},
            // --- Uralic & Baltic siblings --------------------------------
            {"hu", "Magyar", "amikor=when;minden=every;rajta=on;ha=if;kivéve ha=unless;különben=else;ismételd=repeat;for=for;amíg=until;térj vissza=return;akció=action;függvény=function;parancs=command;menü=menu;adj=give;vedd el=take;ölj=kill;sebezz=damage;gyógyíts=heal;teleportálj=teleport;spawnolj=spawn;állítsd be=set;add hozzá=add;vedd ki=remove;mondd=tell;hirdesd=announce;hozd létre=create;töröld=delete;mentsd=save;töltsd be=load;hívd=call;várj=wait;lehűlés=cooldown;repülj=fly;etess=feed;fagyaszd=freeze;gyújtsd meg=ignite;robbanj=explode;tiltd=ban;rúgd ki=kick;ürítsd=clear;csukd be=close;nyisd ki=open;ejtsd=drop;bűvöld=enchant;szereld fel=equip"},
            {"mt", "Malti", "meta=when;kull=every;fuq=on;jekk=if;sakemm ma=unless;inkella=else;irrepeti=repeat;għal=for;sakemm=until;irritorna=return;azzjoni=action;funzjoni=function;kmand=command;menu=menu;agħti=give;ħu=take;aqtillu=kill;weġġa=damage;fejjaq=heal;ittrasporta=teleport;isspawn=spawn;issettja=set;żid=add;neħħi=remove;għid=tell;ħabbar=announce;ħoloq=create;ħassar=delete;issejvja=save;illowdja=load;sejjaħ=call;stenna=wait;tkessiħ=cooldown;itir=fly;itma=feed;iffriża=freeze;aqbad=ignite;isplodi=explode;ibbanja=ban;keċċi=kick;naddaf=clear;agħlaq=close;iftaħ=open;itfa=drop;saħħar=enchant;armer=equip"},
            {"el", "Ελληνικά", "όταν=when;κάθε=every;σε=on;αν=if;εκτός αν=unless;αλλιώς=else;επανάλαβε=repeat;για=for;μέχρι=until;επίστρεψε=return;ενέργεια=action;συνάρτηση=function;εντολή=command;μενού=menu;δώσε=give;πάρε=take;σκότωσε=kill;πλήγωσε=damage;θεράπευσε=heal;τηλεμετέφερε=teleport;δημιούργησε=spawn;όρισε=set;πρόσθεσε=add;αφαίρεσε=remove;πες=tell;ανακοίνωσε=announce;φτιάξε=create;διέγραψε=delete;αποθήκευσε=save;φόρτωσε=load;κάλεσε=call;περίμενε=wait;ψύξη=cooldown;πέτα=fly;τάισε=feed;πάγωσε=freeze;άναψε=ignite;έκρηξη=explode;απαγόρευσε=ban;κλώτσησε=kick;καθάρισε=clear;κλείσε=close;άνοιξε=open;ρίξε=drop;μάγεψε=enchant;εξόπλισε=equip"},
            {"hy", "Հայերեն", "երբ=when;ամեն=every;վրա=on;եթե=if;բացի այն դեպքից=unless;հակառակ դեպքում=else;կրկնիր=repeat;համար=for;մինչև=until;վերադարձրու=return;գործողություն=action;ֆունկցիա=function;հրաման=command;մենյու=menu;տուր=give;վերցրու=take;սպանիր=kill;վնասիր=damage;բուժիր=heal;հեռափոխադրիր=teleport;սպավնիր=spawn;դիր=set;ավելացրու=add;հանիր=remove;ասա=tell;հայտարարիր=announce;ստեղծիր=create;ջնջիր=delete;պահիր=save;բեռնիր=load;կանչիր=call;սպասիր=wait;սառեցում=cooldown;թռիր=fly;կերակրիր=feed;սառեցրու=freeze;վառիր=ignite;պայթեցրու=explode;արգելիր=ban;դուրս շպարիր=kick;մաքրիր=clear;փակիր=close;բացիր=open;գցիր=drop;կախարդիր=enchant;հագցրու=equip"},
            {"ka", "ქართული", "როცა=when;ყოველი=every;ზე=on;თუ=if;თუ არა=unless;სხვაგვარად=else;გაიმეორე=repeat;ამისთვის=for;სანამ=until;დააბრუნე=return;მოქმედება=action;ფუნქცია=function;ბრძანება=command;მენიუ=menu;მიეცი=give;აიღე=take;მოკალი=kill;დააზიანე=damage;განკურნე=heal;გადაინაცვლე=teleport;გამოიძახე=spawn;დააყენე=set;დაამატე=add;მოაშორე=remove;უთხარი=tell;გამოაცხადე=announce;შექმენი=create;წაშალე=delete;შეინახე=save;ჩატვირთე=load;მოუხმე=call;დაელოდე=wait;გაგრილება=cooldown;იფრინე=fly;აჭამე=feed;გაყინე=freeze;წააგზნე=ignite;აფეთქდი=explode;აკრძალე=ban;გააგდე=kick;გაწმინდე=clear;დახურე=close;გახსენი=open;ჩამოაგდე=drop;მოაჯადოვე=enchant;აღჭურვე=equip"},
            {"ar", "العربية", "عندما=when;كل=every;على=on;إذا=if;إلا إذا=unless;وإلا=else;كرر=repeat;لـ=for;حتى=until;أرجع=return;إجراء=action;دالة=function;أمر=command;قائمة=menu;أعط=give;خذ=take;اقتل=kill;أضر=damage;اشفِ=heal;انقل=teleport;استدعي=spawn;اجعل=set;أضف=add;أزل=remove;قل=tell;أعلن=announce;أنشئ=create;احذف=delete;احفظ=save;حمّل=load;نادِ=call;انتظر=wait;تبريد=cooldown;طر=fly;أطعم=feed;جمّد=freeze;أشعل=ignite;انفجر=explode;احظر=ban;اركل=kick;امسح=clear;أغلق=close;افتح=open;أسقط=drop;سحّر=enchant;جهّز=equip"},
            {"he", "עברית", "כאשר=when;כל=every;על=on;אם=if;אלא אם=unless;אחרת=else;חזור=repeat;עבור=for;עד=until;החזר=return;פעולה=action;פונקציה=function;פקודה=command;תפריט=menu;תן=give;קח=take;הרוג=kill;פגע=damage;רפא=heal;שגר=teleport;זמן=spawn;קבע=set;הוסף=add;הסר=remove;אמור=tell;הכרז=announce;צור=create;מחק=delete;שמור=save;טען=load;קרא=call;חכה=wait;קירור=cooldown;עוף=fly;האכל=feed;הקפא=freeze;הבער=ignite;התפוצץ=explode;אסור=ban;בעט=kick;נקה=clear;סגור=close;פתח=open;השלך=drop;כשף=enchant;צייד=equip"},
            {"ur", "اردو", "جب=when;ہر=every;پر=on;اگر=if;جب تک نہیں=unless;ورنہ=else;دہرائیں=repeat;کے لیے=for;تک=until;واپس=return;عمل=action;فنکشن=function;کمانڈ=command;مینو=menu;دو=give;لو=take;مار=kill;نقصان=damage;شفا=heal;ٹیلی پورٹ=teleport;سپان=spawn;رکھو=set;شامل کرو=add;ہٹاؤ=remove;بتاؤ=tell;اعلان=announce;بناؤ=create;حذف=delete;محفوظ=save;لوڈ=load;بلاؤ=call;رکو=wait;کول ڈاؤن=cooldown;اڑ=fly;کھلاؤ=feed;جما دو=freeze;آگ لگا=ignite;دھماکہ=explode;پابندی=ban;نکالو=kick;صاف=clear;بند=close;کھولو=open;گراؤ=drop;جادو=enchant;لگاؤ=equip"},
            {"fa", "فارسی", "وقتی=when;هر=every;روی=on;اگر=if;مگر اینکه=unless;در غیر این صورت=else;تکرار کن=repeat;برای=for;تا=until;بازگردان=return;عملیات=action;تابع=function;دستور=command;منو=menu;بده=give;بردار=take;بکش=kill;آسیب بزن=damage;درمان کن=heal;انتقال بده=teleport;فراخوانی=spawn;قرار بده=set;اضافه کن=add;حذف کن=remove;بگو=tell;اعلام کن=announce;بساز=create;پاک کن=delete;ذخیره کن=save;بارگذاری کن=load;صدا کن=call;صبر کن=wait;خنک‌سازی=cooldown;پرواز کن=fly;تغذیه کن=feed;منجمد کن=freeze;آتش بزن=ignite;منفجر شو=explode;تحریم کن=ban;بیرون کن=kick;پاک کن=clear;ببند=close;باز کن=open;بینداز=drop;افسون کن=enchant;تجهیز کن=equip"},
            {"ku", "Kurdî", "dema=when;her=every;li ser=on;heke=if;heya ku=unless;na=else;dubare bike=repeat;bo=for;heta=until;vegerîne=return;çalakî=action;fonksiyon=function;ferman=command;menû=menu;bide=give;bistîne=take;bikuje=kill;bizîya=damage;baş bike=heal;teleport bike=teleport;spawn bike=spawn;danîne=set;zêde bike=add;jê bibe=remove;bêje=tell;ragihîne=announce;çêke=create;jê bibe=delete;hilîne=save;bar bike=load;bang bike=call;bisekine=wait;sar kirin=cooldown;bifire=fly;xwarin bide=feed;bicemidîne=freeze;agir bike=ignite;teqîne=explode;qedexe bike=ban;derîne=kick;paqij bike=clear;bigre=close;veke=open;bavêje=drop;bisihrîne=enchant;amade bike=equip"},
            {"ps", "پښتو", "کله چې=when;هر=every;پر=on;که=if;مګر که=unless;نور=else;تکرار=repeat;لپاره=for;تر=until;بیرته=return;کړنه=action;فنکشن=function;کمانډ=command;مینو=menu;ورکړه=give;واخله=take;ووژنه=kill;تکلیف=damage;درملنه=heal;تلپورټ=teleport;سپان=spawn;کېږده=set;زیاته=add;لرې=remove;ووايه=tell;اعلان=announce;جوړ=create;ړنګ=delete;ساتنه=save;بار=load;بلنه=call;انتظار=wait;یخوالی=cooldown;الوتنه=fly;خواړه=feed;کنګل=freeze;اور=ignite;چاودنه=explode;بندیز=ban;شړل=kick;پاک=clear;بند=close;خلاص=open;غورځول=drop;جادو=enchant;تجهیز=equip"},
            // --- East & Southeast Asia ------------------------------
            {"zh", "中文", "当=when;每个=every;在=on;如果=if;除非=unless;否则=else;重复=repeat;对于=for;直到=until;返回=return;动作=action;函数=function;命令=command;菜单=menu;给=give;拿=take;杀死=kill;伤害=damage;治疗=heal;传送=teleport;生成=spawn;设置=set;添加=add;移除=remove;告诉=tell;宣布=announce;创建=create;删除=delete;保存=save;加载=load;调用=call;等待=wait;冷却=cooldown;飞行=fly;喂食=feed;冻结=freeze;点燃=ignite;爆炸=explode;封禁=ban;踢出=kick;清除=clear;关闭=close;打开=open;掉落=drop;附魔=enchant;装备=equip"},
            {"ja", "日本語", "とき=when;ごと=every;で=on;もし=if;ない限り=unless;それ以外=else;繰り返す=repeat;のため=for;まで=until;戻す=return;アクション=action;関数=function;コマンド=command;メニュー=menu;与える=give;取る=take;殺す=kill;傷つける=damage;治す=heal;テレポート=teleport;スポーン=spawn;設定=set;追加=add;削除=remove;伝える=tell;発表=announce;作成=create;削除=delete;保存=save;読み込み=load;呼ぶ=call;待つ=wait;クールダウン=cooldown;飛ぶ=fly;餌を与える=feed;凍らせる=freeze;点火=ignite;爆発=explode;禁止=ban;追放=kick;クリア=clear;閉じる=close;開く=open;落とす=drop;エンチャント=enchant;装備=equip"},
            {"ko", "한국어", "때=when;마다=every;에=on;만약=if;하지 않는 한=unless;그렇지 않으면=else;반복=repeat;위해=for;까지=until;반환=return;동작=action;함수=function;명령=command;메뉴=menu;주다=give;가져가다=take;죽이다=kill;손상=damage;치유=heal;순간이동=teleport;소환=spawn;설정=set;추가=add;제거=remove;말하다=tell;알리다=announce;생성=create;삭제=delete;저장=save;불러오기=load;호출=call;기다리다=wait;쿨다운=cooldown;날다=fly;먹이다=feed;얼리다=freeze;점화=ignite;폭발=explode;차단=ban;추방=kick;정리=clear;닫다=close;열다=open;떨어뜨리다=drop;인챈트=enchant;장비=equip"},
            {"vi", "Tiếng Việt", "khi=when;mỗi=every;trên=on;nếu=if;trừ khi=unless;nếu không=else;lặp lại=repeat;cho=for;cho đến khi=until;trả về=return;hành động=action;hàm=function;lệnh=command;menu=menu;cho=give;lấy=take;giết=kill;gây sát thương=damage;chữa lành=heal;dịch chuyển=teleport;triệu hồi=spawn;đặt=set;thêm=add;gỡ bỏ=remove;nói=tell;công bố=announce;tạo=create;xóa=delete;lưu=save;tải=load;gọi=call;chờ=wait;hồi chiêu=cooldown;bay=fly;cho ăn=feed;đóng băng=freeze;đốt=ignite;nổ=explode;cấm=ban;đuổi=kick;dọn=clear;đóng=close;mở=open;thả=drop;phù phép=enchant;trang bị=equip"},
            {"th", "ไทย", "เมื่อ=when;ทุก=every;บน=on;ถ้า=if;เว้นแต่=unless;มิฉะนั้น=else;ทำซ้ำ=repeat;สำหรับ=for;จนกระทั่ง=until;คืนค่า=return;การกระทำ=action;ฟังก์ชัน=function;คำสั่ง=command;เมนู=menu;ให้=give;หยิบ=take;ฆ่า=kill;สร้างความเสียหาย=damage;รักษา=heal;เทเลพอร์ต=teleport;เรียก=spawn;ตั้ง=set;เพิ่ม=add;ลบ=remove;บอก=tell;ประกาศ=announce;สร้าง=create;ลบ=delete;บันทึก=save;โหลด=load;เรียก=call;รอ=wait;คูลดาวน์=cooldown;บิน=fly;ป้อนอาหาร=feed;แช่แข็ง=freeze;จุดไฟ=ignite;ระเบิด=explode;แบน=ban;เตะ=kick;ล้าง=clear;ปิด=close;เปิด=open;ปล่อย=drop;ร่ายมนตร์=enchant;สวม=equip"},
            {"id", "Bahasa Indonesia", "ketika=when;setiap=every;pada=on;jika=if;kecuali=unless;jika tidak=else;ulangi=repeat;untuk=for;hingga=until;kembalikan=return;aksi=action;fungsi=function;perintah=command;menu=menu;beri=give;ambil=take;bunuh=kill;lukai=damage;sembuhkan=heal;teleport=teleport;spawn=spawn;atur=set;tambah=add;hapus=remove;bilang=tell;umumkan=announce;buat=create;hapus=delete;simpan=save;muat=load;panggil=call;tunggu=wait;dingin=cooldown;terbang=fly;beri makan=feed;bekukan=freeze;bakar=ignite;meledak=explode;larang=ban;tendang=kick;bersihkan=clear;tutup=close;buka=open;jatuhkan=drop;pesona=enchant;lengkapi=equip"},
            {"ms", "Bahasa Melayu", "apabila=when;setiap=every;pada=on;jika=if;melainkan=unless;jika tidak=else;ulang=repeat;untuk=for;sehingga=until;kembali=return;tindakan=action;fungsi=function;arahan=command;menu=menu;beri=give;ambil=take;bunuh=kill;cedera=damage;sembuh=heal;teleport=teleport;spawn=spawn;tetapkan=set;tambah=add;buang=remove;beritahu=tell;umumkan=announce;cipta=create;padam=delete;simpan=save;muat=load;panggil=call;tunggu=wait;sejuk=cooldown;terbang=fly;beri makan=feed;beku=freeze;bakar=ignite;meletup=explode;haram=ban;sepakan=kick;bersih=clear;tutup=close;buka=open;jatuh=drop;pesona=enchant;lengkap=equip"},
            {"tl", "Tagalog", "kapag=when;bawat=every;sa=on;kung=if;maliban kung=unless;kung hindi=else;ulitin=repeat;para=for;hanggang=until;ibalik=return;aksyon=action;punksyon=function;utos=command;menu=menu;bigyan=give;kunin=take;patayin=kill;masaktan=damage;gumaling=heal;teleport=teleport;summon=spawn;itakda=set;idagdag=add;alisin=remove;sabihin=tell;anunsyo=announce;gumawa=create;burahin=delete;i-save=save;i-load=load;tawagin=call;maghintay=wait;cooldown=cooldown;lumipad=fly;pakainin=feed;i-freeze=freeze;sunugin=ignite;sumabog=explode;ban=ban;sisipain=kick;linisin=clear;isara=close;buksan=open;ihulog=drop;enchat=enchant;magbigay-kasangkapan=equip"},
            {"my", "မြန်မာ", "အခါ=when;တိုင်း=every;ပေါ်=on;လျှင်=if;မဟုတ်လျှင်=unless;မဟုတ်ရင်=else;ထပ်လုပ်=repeat;အတွက်=for;အထိ=until;ပြန်ပေး=return;လုပ်ဆောင်ချက်=action;လုပ်ငန်းစဉ်=function;ကွန်မန်း=command;မီနူး=menu;ပေး=give;ယူ=take;သတ်=kill;ထိခိုက်=damage;ကုသ=heal;တယ်လီပို့=teleport;ခေါ်=spawn;သတ်မှတ်=set;ထည့်=add;ဖယ်=remove;ပြော=tell;ကြေညာ=announce;ဖန်တီး=create;ဖျက်=delete;သိမ်း=save;တင်=load;ခေါ်=call;စောင့်=wait;အအေးခံ=cooldown;ပျံ=fly;ကျွေး=feed;အေးခဲ=freeze;မီးရှို့=ignite;ပေါက်ကွဲ=explode;ပိတ်ပင်=ban;ကန်=kick;ရှင်း=clear;ပိတ်=close;ဖွင့်=open;ချ=drop;စာလုံး=enchant;တပ်ဆင်=equip"},
            {"km", "ខ្មែរ", "ពេល=when;រាល់=every;លើ=on;ប្រសិនបើ=if;លុះត្រាតែ=unless;បើមិនដូច្នេះ=else;ធ្វើម្តងទៀត=repeat;សម្រាប់=for;រហូតដល់=until;ត្រឡប់=return;សកម្មភាព=action;មុខងារ=function;ពាក្យបញ្ជា=command;ម៉ឺនុយ=menu;ផ្តល់=give;យក=take;សម្លាប់=kill;បំផ្លាញ=damage;ព្យាបាល=heal;តេលេប៉ត=teleport;ហៅ=spawn;កំណត់=set;បន្ថែម=add;ដក=remove;ប្រាប់=tell;ប្រកាស=announce;បង្កើត=create;លុប=delete;រក្សាទុក=save;ផ្ទុក=load;ហៅ=call;រង់ចាំ=wait;ត្រជាក់=cooldown;ហោះ=fly;ចិញ្ចឹម=feed;កក=freeze;ដុត=ignite;ផ្ទុះ=explode;ហាមឃាត់=ban;ទាត់=kick;សម្អាត=clear;បិទ=close;បើក=open;ទម្លាក់=drop;អក្ខរាវិរុទ្ធ=enchant;បំពាក់=equip"},
            {"lo", "ລາວ", "ເມື່ອ=when;ທຸກ=every;ເທິງ=on;ຖ້າ=if;ເວັ້ນເສຍແຕ່=unless;ຖ້າບໍ່ດັ່ງນັ້ນ=else;ເຮັດຊ້ຳ=repeat;ສຳລັບ=for;ຈົນກະທັ່ງ=until;ກັບຄືນ=return;ການກະທຳ=action;ຟັງຊັ່ນ=function;ຄຳສັ່ງ=command;ເມນູ=menu;ໃຫ້=give;ເອົາ=take;ຂ້າ=kill;ທຳລາຍ=damage;ປິ່ນປົວ=heal;ໂທລະເລັກ=teleport;ເອີ້ນ=spawn;ຕັ້ງ=set;ເພີ່ມ=add;ເອົາອອກ=remove;ບອກ=tell;ປະກາດ=announce;ສ້າງ=create;ລຶບ=delete;ບັນທຶກ=save;ໂຫຼດ=load;ເອີ້ນ=call;ລໍຖ້າ=wait;ເຢັນລົງ=cooldown;ບິນ=fly;ໃຫ້ອາຫານ=feed;ແຊ່ແຂງ=freeze;ຈູດ=ignite;ລະເບີດ=explode;ຫ້າມ=ban;ເຕະ=kick;ເຮັດຄວາມສະອາດ=clear;ປິດ=close;ເປີດ=open;ຖິ້ມ=drop;ສະກົດ=enchant;ຕິດຕັ້ງ=equip"},
            {"mn", "Монгол", "үед=when;бүр=every;дээр=on;хэрэв=if;хэрэв үгүй бол=unless;эс тэгвэл=else;давт=repeat;тулд=for;хүртэл=until;буцаа=return;үйлдэл=action;функц=function;команд=command;цэс=menu;өг=give;ав=take;ал=kill;гэмтээ=damage;эмчил=heal;телепорт=teleport;спавн=spawn;тохируул=set;нэм=add;арилга=remove;хэл=tell;зарла=announce;бүтээ=create;устга=delete;хадгал=save;ачаал=load;дууд=call;хүлээ=wait;хөргөлт=cooldown;нис=fly;тэжээ=feed;хөлдөө=freeze;галд=ignite;дэлбэлд=explode;хоригло=ban;өшигнө=kick;цэвэрлэ=clear;хаа=close;нээ=open;унага=drop;шившлэ=enchant;тоногло=equip"},
            // --- South Asia & Dravidian ------------------------------------
            {"hi", "हिन्दी", "जब=when;हर=every;पर=on;अगर=if;जब तक नहीं=unless;अन्यथा=else;दोहराएं=repeat;के लिए=for;जब तक=until;लौटाओ=return;क्रिया=action;फ़ंक्शन=function;कमांड=command;मेनू=menu;दो=give;लो=take;मारो=kill;नुकसान=damage;ठीक करो=heal;टेलीपोर्ट=teleport;स्पॉन=spawn;सेट करो=set;जोड़ो=add;हटाओ=remove;बताओ=tell;घोषणा=announce;बनाओ=create;मिटाओ=delete;सहेजो=save;लोड करो=load;बुलाओ=call;रुको=wait;कूलडाउन=cooldown;उड़ो=fly;खिलाओ=feed;जमाओ=freeze;जलाओ=ignite;विस्फोट=explode;प्रतिबंध=ban;निकालो=kick;साफ़=clear;बंद=close;खोलो=open;गिराओ=drop;मोहित=enchant;सजाओ=equip"},
            {"bn", "বাংলা", "যখন=when;প্রতি=every;উপর=on;যদি=if;যদি না=unless;অন্যথায়=else;পুনরাবৃত্তি=repeat;জন্য=for;যতক্ষণ=until;ফিরাও=return;কর্ম=action;ফাংশন=function;কমান্ড=command;মেনু=menu;দাও=give;নাও=take;মারো=kill;ক্ষতি=damage;সুস্থ করো=heal;টেলিপোর্ট=teleport;স্পন=spawn;সেট=set;যোগ=add;বাদ=remove;বলো=tell;ঘোষণা=announce;তৈরি=create;মুছো=delete;সংরক্ষণ=save;লোড=load;ডাকো=call;অপেক্ষা=wait;কুলডাউন=cooldown;উড়ো=fly;খাওয়াও=feed;জমাও=freeze;জ্বালাও=ignite;বিস্ফোরণ=explode;নিষিদ্ধ=ban;বের করো=kick;পরিষ্কার=clear;বন্ধ=close;খোলো=open;ফেলো=drop;মন্ত্র=enchant;সাজাও=equip"},
            {"te", "తెలుగు", "ఎప్పుడు=when;ప్రతి=every;మీద=on;ఒకవేళ=if;తప్ప=unless;లేకపోతే=else;పునరావృతం=repeat;కోసం=for;వరకు=until;తిరిగి=return;చర్య=action;ఫంక్షన్=function;ఆదేశం=command;మెనూ=menu;ఇవ్వు=give;తీసుకో=take;చంపు=kill;దెబ్బ=damage;నయం=heal;టెలీపోర్ట్=teleport;స్పాన్=spawn;సెట్=set;జోడించు=add;తొలగించు=remove;చెప్పు=tell;ప్రకటించు=announce;సృష్టించు=create;తొలగించు=delete;సేవ్=save;లోడ్=load;పిలవు=call;వేచి=wait;కూల్డౌన్=cooldown;ఎగరు=fly;తినిపించు=feed;స్తంభింపజేయి=freeze;మండించు=ignite;పేల్చు=explode;నిషేధించు=ban;తన్ను=kick;శుభ్రం=clear;మూసివేయి=close;తెరువు=open;వేయి=drop;మంత్ర=enchant;సన్నద్ధం=equip"},
            {"ta", "தமிழ்", "எப்போது=when;ஒவ்வொரு=every;மேல்=on;என்றால்=if;வரை=unless;இல்லையெனில்=else;மீண்டும்=repeat;க்கு=for;வரை=until;திரும்பு=return;செயல்=action;செயல்பாடு=function;கட்டளை=command;மெனு=menu;கொடு=give;எடு=take;கொல்=kill;சேதம்=damage;குணமாக்கு=heal;தொலைதூரம்=teleport;ஸ்பான்=spawn;அமை=set;சேர்=add;அகற்று=remove;சொல்=tell;அறிவி=announce;உருவாக்கு=create;நீக்கு=delete;சேமி=save;ஏற்று=load;அழை=call;காத்திரு=wait;கூல்டவுன்=cooldown;பற=fly;உணவூட்டு=feed;உறையவை=freeze;தீ=ignite;வெடி=explode;தடை=ban;உதை=kick;சுத்தம்=clear;மூடு=close;திற=open;போடு=drop;மந்திரம்=enchant;தயார்=equip"},
            {"kn", "ಕನ್ನಡ", "ಯಾವಾಗ=when;ಪ್ರತಿ=every;ಮೇಲೆ=on;ವೇಳೆ=if;ಹೊರತು=unless;ಇಲ್ಲದಿದ್ದರೆ=else;ಪುನರಾವರ್ತಿಸು=repeat;ಗಾಗಿ=for;ತನಕ=until;ಹಿಂತಿರುಗಿ=return;ಕ್ರಿಯೆ=action;ಕಾರ್ಯ=function;ಆಜ್ಞೆ=command;ಮೆನು=menu;ಕೊಡು=give;ತೆಗೆದುಕೊಳ್ಳು=take;ಕೊಲ್ಲು=kill;ಹಾನಿ=damage;ಗುಣಪಡಿಸು=heal;ಟೆಲಿಪೋರ್ಟ್=teleport;ಸ್ಪಾನ್=spawn;ಹೊಂದಿಸು=set;ಸೇರಿಸು=add;ತೆಗೆ=remove;ಹೇಳು=tell;ಘೋಷಿಸು=announce;ರಚಿಸು=create;ಅಳಿಸು=delete;ಉಳಿಸು=save;ಲೋಡ್=load;ಕರೆ=call;ನಿರೀಕ್ಷಿಸು=wait;ಕೂಲ್ಡೌನ್=cooldown;ಹಾರು=fly;ಆಹಾರ=feed;ಫ್ರೀಜ್=freeze;ಉರಿಸು=ignite;ಸ್ಫೋಟ=explode;ನಿಷೇಧ=ban;ಒದಿ=kick;ಸ್ವಚ್ಛ=clear;ಮುಚ್ಚು=close;ತೆರೆ=open;ಬಿಡು=drop;ಮಂತ್ರ=enchant;ಸಜ್ಜು=equip"},
            {"ml", "മലയാളം", "എപ്പോൾ=when;ഓരോ=every;മുകളിൽ=on;എങ്കിൽ=if;അല്ലാതെ=unless;അല്ലെങ്കിൽ=else;ആവർത്തിക്കുക=repeat;വേണ്ടി=for;വരെ=until;തിരികെ=return;പ്രവർത്തനം=action;ഫങ്ഷൻ=function;കമാൻഡ്=command;മെനു=menu;കൊടുക്കുക=give;എടുക്കുക=take;കൊല്ലുക=kill;നാശം=damage;ചികിത്സ=heal;ടെലിപോർട്ട്=teleport;സ്പോൺ=spawn;സജ്ജമാക്കുക=set;ചേർക്കുക=add;നീക്കം=remove;പറയുക=tell;പ്രഖ്യാപിക്കുക=announce;സൃഷ്ടിക്കുക=create;ഇല്ലാതാക്കുക=delete;സംരക്ഷിക്കുക=save;ലോഡ്=load;വിളിക്കുക=call;കാത്തിരിക്കുക=wait;കൂൾഡൗൺ=cooldown;പറക്കുക=fly;ഭക്ഷണം=feed;ഫ്രീസ്=freeze;കത്തിക്കുക=ignite;സ്ഫോടനം=explode;നിരോധനം=ban;ചവിട്ടുക=kick;വൃത്തിയാക്കുക=clear;അടയ്ക്കുക=close;തുറക്കുക=open;ഇടുക=drop;മന്ത്രം=enchant;സജ്ജീകരിക്കുക=equip"},
            {"gu", "ગુજરાતી", "જ્યારે=when;દરેક=every;પર=on;જો=if;સિવાય=unless;અન્યથા=else;પુનરાવર્તન=repeat;માટે=for;સુધી=until;પાછા=return;ક્રિયા=action;કાર્ય=function;આદેશ=command;મેનુ=menu;આપો=give;લો=take;મારી નાખો=kill;નુકસાન=damage;સાજા કરો=heal;ટેલિપોર્ટ=teleport;સ્પોન=spawn;સેટ=set;ઉમેરો=add;દૂર કરો=remove;કહો=tell;જાહેર=announce;બનાવો=create;કાઢી નાખો=delete;સાચવો=save;લોડ=load;બોલાવો=call;રાહ જુઓ=wait;કૂલડાઉન=cooldown;ઉડો=fly;ખવડાવો=feed;સ્થિર કરો=freeze;સળગાવો=ignite;વિસ્ફોટ=explode;પ્રતિબંધ=ban;લાત=kick;સાફ=clear;બંધ=close;ખોલો=open;મૂકો=drop;મંત્ર=enchant;સજ્જ=equip"},
            {"mr", "मराठी", "जेव्हा=when;प्रत्येक=every;वर=on;जर=if;जोपर्यंत नाही=unless;अन्यथा=else;पुन्हा करा=repeat;साठी=for;पर्यंत=until;परत=return;क्रिया=action;कार्य=function;आदेश=command;मेनू=menu;द्या=give;घ्या=take;मारा=kill;नुकसान=damage;बरे करा=heal;टेलीपोर्ट=teleport;स्पॉन=spawn;सेट=set;जोडा=add;काढा=remove;सांगा=tell;घोषणा=announce;तयार करा=create;हटवा=delete;जतन=save;लोड=load;बोलावा=call;थांबा=wait;कूलडाउन=cooldown;उडा=fly;खाऊ घाला=feed;गोठवा=freeze;पेटवा=ignite;स्फोट=explode;प्रतिबंध=ban;लाथ=kick;स्वच्छ=clear;बंद=close;उघडा=open;टाका=drop;मंत्र=enchant;सज्जा=equip"},
            {"pa", "ਪੰਜਾਬੀ", "ਜਦੋਂ=when;ਹਰ=every;ਉੱਤੇ=on;ਜੇ=if;ਜਦੋਂ ਤੱਕ ਨਹੀਂ=unless;ਨਹੀਂ ਤਾਂ=else;ਦੁਹਰਾਓ=repeat;ਲਈ=for;ਤੱਕ=until;ਵਾਪਸ=return;ਕਿਰਿਆ=action;ਫੰਕਸ਼ਨ=function;ਕਮਾਂਡ=command;ਮੀਨੂ=menu;ਦਿਓ=give;ਲਓ=take;ਮਾਰੋ=kill;ਨੁਕਸਾਨ=damage;ਠੀਕ ਕਰੋ=heal;ਟੈਲੀਪੋਰਟ=teleport;ਸਪੌਨ=spawn;ਸੈੱਟ=set;ਜੋੜੋ=add;ਹਟਾਓ=remove;ਦੱਸੋ=tell;ਘੋਸ਼ਣਾ=announce;ਬਣਾਓ=create;ਮਿਟਾਓ=delete;ਸੰਭਾਲੋ=save;ਲੋਡ=load;ਬੁਲਾਓ=call;ਰੁਕੋ=wait;ਕੂਲਡਾਊਨ=cooldown;ਉੱਡੋ=fly;ਖਵਾਓ=feed;ਜੰਮੋ=freeze;ਬਾਲੋ=ignite;ਧਮਾਕਾ=explode;ਬੈਨ=ban;ਲੱਤ=kick;ਸਾਫ਼=clear;ਬੰਦ=close;ਖੋਲ੍ਹੋ=open;ਸੁੱਟੋ=drop;ਮੰਤਰ=enchant;ਸਜਾਓ=equip"},
            {"si", "සිංහල", "කවදා=when;සෑම=every;මත=on;නම්=if;හැරුණු විට=unless;එසේ නොමැතිනම්=else;නැවත=repeat;සඳහා=for;තෙක්=until;ආපසු=return;ක්රියාව=action;ශ්‍රිතය=function;විධානය=command;මෙනුව=menu;දෙන්න=give;ගන්න=take;මරන්න=kill;හානි=damage;සුව=heal;ටෙලිපෝර්ට්=teleport;ස්පෝන්=spawn;සකසන්න=set;එකතු=add;ඉවත්=remove;කියන්න=tell;ප්‍රකාශ=announce;සාදන්න=create;මකන්න=delete;සුරකින්න=save;පූරණය=load;අමතන්න=call;රැඳී=wait;කූල්ඩවුන්=cooldown;පියාසර=fly;කවන්න=feed;කැටි=freeze;ගිනි=ignite;පිපිරුම්=explode;තහනම්=ban;පයින්=kick;පිරිසිදු=clear;වසන්න=close;විවෘත=open;දමන්න=drop;මන්ත්‍ර=enchant;සන්නද්ධ=equip"},
            {"ne", "नेपाली", "जब=when;हरेक=every;मा=on;यदि=if;बाहेक=unless;अन्यथा=else;दोहोर्‍याउनु=repeat;लागि=for;सम्म=until;फिर्ता=return;क्रिया=action;प्रकार्य=function;आदेश=command;मेनु=menu;दिनु=give;लिनु=take;मार्नु=kill;क्षति=damage;निको=heal;टेलिपोर्ट=teleport;स्पान=spawn;सेट=set;थप्नु=add;हटाउनु=remove;भन्नु=tell;घोषणा=announce;बनाउनु=create;मेटाउनु=delete;बचत=save;लोड=load;बोलाउनु=call;पर्खनु=wait;कुलडाउन=cooldown;उड्नु=fly;खुवाउनु=feed;जम्नु=freeze;बाल्नु=ignite;विस्फोट=explode;प्रतिबन्ध=ban;लात=kick;सफा=clear;बन्द=close;खोल्नु=open;झार्नु=drop;मन्त्र=enchant;सुसज्जित=equip"},
            // --- Africa & South Hemisphere ---------------------------------
            {"sw", "Kiswahili", "wakati=when;kila=every;juu=on;kama=if;isipokuwa=unless;vinginevyo=else;rudia=repeat;kwa=for;hadi=until;rudi=return;hatua=action;kazi=function;amri=command;menyu=menu;pa=give;chukua=take;ua=kill;haribu=damage;poneya=heal;teleport=teleport;spawn=spawn;weka=set;ongeza=add;ondoa=remove;mwambie=tell;tangaza=announce;umba=create;futa=delete;hifadhi=save;pakia=load;piga=call;ngoja=wait;baridi=cooldown;ruka=fly;lishe=feed;gandisha=freeze;washa=ignite;lipuka=explode;piga marufuku=ban;tega=kick;safisha=clear;funga=close;fungua=open;angusha=drop;roga=enchant;vaa=equip"},
            {"zu", "isiZulu", "uma=when;yonke=every;phezu=on;uma=if;ngaphandle kokuthi=unless;ngaphandle kwalokho=else;phinda=repeat;ngoba=for;kuze kube=until;buyisa=return;isenzo=action;umsebenzi=function;umyalo=command;imenyu=menu;nika=give;thatha=take;bulala=kill;limaza=damage;philisa=heal;teleport=teleport;spawn=spawn;beka=set;engeza=add;susa=remove;tshela=tell;memeza=announce;dala=create;sula=delete;gcina=save;layisha=load;biza=call;linda=wait;ukuphola=cooldown;ndiza=fly;ondla=feed;qandisa=freeze;basa=ignite;qhuma=explode;vala=ban;khipha=kick;hlanza=clear;vala=close;vula=open;phonsa=drop;thakatha=enchant;faka=equip"},
            {"xh", "isiXhosa", "xa=when;yonke=every;phezu=on;ukuba=if;ngaphandle kwakuba=unless;kungenjalo=else;phinda=repeat;ngoba=for;kude kube=until;buyisela=return;intshukumo=action;umsebenzi=function;umyalelo=command;imenyu=menu;nika=give;thatha=take;bulala=kill;limaza=damage;philisa=heal;teleport=teleport;spawn=spawn;beka=set;ongeza=add;susa=remove;xelela=tell;memezela=announce;yila=create;cima=delete;gcina=save;layisha=load;biza=call;linda=wait;ukupholisa=cooldown;bhabha=fly;ondla=feed;qandisa=freeze;basa=ignite;qhuma=explode;vala=ban;khupha=kick;hlamba=clear;vala=close;vula=open;phosa=drop;loya=enchant;faka=equip"},
            {"af", "Afrikaans", "wanneer=when;elke=every;op=on;as=if;tensy=unless;anders=else;herhaal=repeat;vir=for;totdat=until;keer terug=return;aksie=action;funksie=function;opdrag=command;spyskaart=menu;gee=give;neem=take;doodmaak=kill;beskadig=damage;genees=heal;teleporteer=teleport;spawn=spawn;stel=set;voeg by=add;verwyder=remove;vertel=tell;kondig aan=announce;skep=create;verwyder=delete;stoor=save;laai=load;roep=call;wag=wait;afkoeling=cooldown;vlieg=fly;voer=feed;bevries=freeze;steek aan=ignite;ontplof=explode;verban=ban;skop=kick;maak skoon=clear;sluit=close;maak oop=open;laat val=drop;betower=enchant;rus toe=equip"},
            {"st", "Sesotho", "ha=when;e mong le e mong=every;holim=on;haeba=if;ntle le ha=unless;ho seng joalo=else;pheta=repeat;bakeng=for;ho fihlela=until;khutlisa=return;ketso=action;mosebetsi=function;taelo=command;menu=menu;fa=give;nka=take;bolaea=kill;senya=damage;folisa=heal;teleport=teleport;spawn=spawn;beha=set;kenya=add;tlosa=remove;bolella=tell;phatlalatsa=announce;etsa=create;hlakola=delete;boloka=save;jarolla=load;bitsa=call;emela=wait;phomolo=cooldown;fofa=fly;fepa=feed;hoamisa=freeze;tjhesa=ignite;qhomisa=explode;thibela=ban;raha=kick;hloekisa=clear;koala=close;bula=open;lahla=drop;loya=enchant;hlomella=equip"},
            {"sn", "Shona", "kana=when;imwe neimwe=every;pamusoro=on;kana=if;kunze kwokuti=unless;zvikasadaro=else;dzokorora=repeat;kuti=for;kusvikira=until;dzokera=return;chiito=action;basa=function;murairo=command;menu=menu;ipa=give;tora=take;uraya=kill;kuvadza=damage;rapa=heal;teleport=teleport;spawn=spawn;isa=set;wedzera=add;bvisa=remove;udza=tell;zvizivise=announce;gadzira=create;dima=delete;chengeta=save;tora=load;dana=call;mirira=wait;kutonhodza=cooldown;bhururuka=fly;fudza=feed;nezeza=freeze;batsa=ignite;putika=explode;rambidza=ban;kandira=kick;chenesa=clear;vhara=close;vhura=open;donhedza=drop;roya=enchant;gadzirira=equip"},
            {"so", "Soomaali", "marka=when;kasta=every;kor=on;haddii=if;haddii aan=unless;haddii kale=else;ku celi=repeat;si=for;ilaa=until;soo celi=return;fal=action;shaqayn=function;amar=command;menu=menu;si=give;qaad=take;dil=kill;dhaawac=damage;dawayso=heal;teleport=teleport;spawn=spawn;deji=set;ku dar=add;ka saar=remove;sheeg=tell;ku dhawaaq=announce;abuur=create;tirtir=delete;kaydi=save;soo geli=load;u yeer=call;sug=wait;qabow=cooldown;duul=fly;quudi=feed;baraf=freeze;shid=ignite;qarax=explode;mammac=ban;laad=kick;nadiifi=clear;xir=close;fur=open;tuur=drop;sixir=enchant;qalab=equip"},
            {"am", "አማርኛ", "ሲ=when;እያንዳንዱ=every;ላይ=on;ከሆነ=if;ካልሆነ=unless;አለበለዚያ=else;ደግም=repeat;ለ=for;እስከ=until;ተመልስ=return;እርምጃ=action;ተግባር=function;ትእዛዝ=command;ምናሌ=menu;ስጥ=give;ውሰድ=take;ግደል=kill;ጉዳት=damage;ፈውስ=heal;ቴሌፖርት=teleport;ስፓውን=spawn;አዘጋጅ=set;ጨምር=add;አስወግድ=remove;ንገር=tell;አስታውቅ=announce;ፍጠር=create;ሰርዝ=delete;አስቀምጥ=save;ጫን=load;ጥራ=call;ጠብቅ=wait;ቅዝቃዜ=cooldown;በር=fly;አብላ=feed;ቀዝቅዝ=freeze;አቃጥል=ignite;ፈንዳ=explode;ከልክል=ban;ምታ=kick;አጽዳ=clear;ዝጋ=close;ክፈት=open;ጣል=drop;ጥበቃ=enchant;አስታጥቅ=equip"},
            {"rw", "Kinyarwanda", "iyo=when;buri=every;ku=on;niba=if;keretse=unless;ubundi=else;subiramo=repeat;ku=for;kugeza=until;subira=return;igikorwa=action;imikorere=function;itegeko=command;menu=menu;ha=give;fata=take;icisha=kill;angiza=damage;kiza=heal;teleport=teleport;spawn=spawn;shyira=set;ongeraho=add;kuraho=remove;bwira=tell;menyesha=announce;kora=create;siba=delete;bika=save;pakira=load;hamagara=call;tegereza=wait;gukonja=cooldown;guruka=fly;gaburira=feed;konja=freeze;watsa=ignite;turika=explode;bujja=ban;tera=kick;isukura=clear;funga=close;fungura=open;jugunya=drop;roga=enchant;shyiraho=equip"},
            {"mg", "Malagasy", "rehefa=when;isaky=every;eo=on;raha=if;raha tsy=unless;raha tsy izany=else;avereno=repeat;ho=for;mandra-pahatongan=until;avereno=return;hetsika=action;fampiasa=function;baiko=command;menu=menu;omeo=give;alao=take;vonoy=kill;manaikitra=damage;sitrano=heal;teleport=teleport;spawn=spawn;apetraho=set;ampio=add;esory=remove;lazao=tell;ambaraka=announce;foronina=create;fafana=delete;tehirizo=save;entana=load;antsoy=call;andraso=wait;fihenam-bidy=cooldown;manidina=fly;omahy=feed;mangatsiaka=freeze;hirepo=ignite;mipoaka=explode;rara=ban;daka=kick;diosy=clear;akaty=close;sokafy=open;avoy=drop;odina=enchant;omezana=equip"},
            {"ny", "Chichewa", "pamene=when;alionsera=every;pa=on;ngati=if;pokhapokha=unless;zina=else;bwereza=repeat;chifukwa=for;mpaka=until;bwerera=return;zochita=action;ntchito=function;lamulo=command;menyu=menu;patsa=give;tenga=take;pha=kill;vwala=damage;chiritsa=heal;teleport=teleport;spawn=spawn;ika=set;onjezera=add;chotsa=remove;uza=tell;lengesa=announce;panga=create;fufuta=delete;suma=save;kwezani=load;itana=call;dikira=wait;kuzizira=cooldown;uluka=fly;dyetsa=feed;undana=freeze;yatsa=ignite;phulika=explode;letsa=ban;menya=kick;tsuka=clear;tseka=close;tsegula=open;ponya=drop;matsenga=enchant;veketsa=equip"},
            {"yo", "Yorùbá", "nigba=when;gbogbo=every;lori=on;ti=if;ayafi=unless;bibẹẹkọ=else;tun ṣe=repeat;fun=for;titi=until;da pada=return;iṣe=action;iṣẹ=function;aṣẹ=command;menu=menu;fun=give;mu=take;pa=kill;ṣe ipalara=damage;wòsàn=heal;teleport=teleport;spawn=spawn;ṣeto=set;fi kun=add;yọ kuro=remove;sọ=tell;kede=announce;ṣẹda=create;pa rẹ=delete;fi pamọ=save;gba=load;pe=call;duro=wait;itutu=cooldown;fò=fly;jẹun=feed;dì=freeze;jona=ignite;bugbamu=explode;gbele=ban;tapa=kick;nu=clear;tì=close;ṣii=open;ju=drop;ọkàn=enchant;mura=equip"},
            {"ig", "Igbo", "mgbe=when;ọbụla=every;na=on;ọ bụrụ=if;ọ gwụla ma=unless;ma ọ bụghị=else;megharịa=repeat;maka=for;ruo=until;weghachi=return;omume=action;ọrụ=function;iwu=command;menu=menu;nye=give;were=take;gbue=kill;merụọ=damage;gwọọ=heal;teleport=teleport;spawn=spawn;dozie=set;gbakwunye=add;wepụ=remove;gwa=tell;kpọsaa=announce;mepụta=create;hichapụ=delete;chekwa=save;kwado=load;kpọ=call;cere=wait;jụrụ oyi=cooldown;fefee=fly;nye nri=feed;gbochie=freeze;gbanye ọkụ=ignite;gbawara=explode;machị=ban;gbaa=kick;sachaa=clear;mechie=close;meghee=open;tụfuo=drop;gbaa afa=enchant;kwado=equip"},
            {"ha", "Hausa", "lokacin=when;kowane=every;a kan=on;idan=if;sai dai=unless;in ba haka ba=else;maimaita=repeat;don=for;har=until;mayar=return;aiki=action;aiki=function;umurni=command;menu=menu;ba=give;ɗauka=take;kashe=kill;lalata=damage;warkar=heal;teleport=teleport;spawn=spawn;sa=set;ƙara=add;cire=remove;faɗa=tell;sanar=announce;ƙirƙira=create;share=delete;ajiye=save;loda=load;kira=call;jira=wait;sanyaya=cooldown;tashi=fly;ciyar=feed;daskare=freeze;kona=ignite;fashewa=explode;daka=ban;buda=kick;tsafta=clear;rufe=close;buɗe=open;fadi=drop;sihiri=enchant;shirya=equip"},
            // --- Austronesian & Pacific -------------------------------------
            {"fil", "Filipino", "kapag=when;bawat=every;sa=on;kung=if;maliban kung=unless;kung hindi=else;ulitin=repeat;para sa=for;hanggang=until;ibalik=return;aksyon=action;punksyon=function;utos=command;menu=menu;ibigay=give;kunin=take;patayin=kill;masaktan=damage;gumaling=heal;teleport=teleport;summon=spawn;itakda=set;idagdag=add;alisin=remove;sabihin=tell;ipahayag=announce;gumawa=create;burahin=delete;i-save=save;i-load=load;tawagin=call;maghintay=wait;cooldown=cooldown;lumipad=fly;pakainin=feed;i-freeze=freeze;sunugin=ignite;sumabog=explode;bawal=ban;sisipain=kick;linisin=clear;isara=close;buksan=open;ihulog=drop;mangkulam=enchant;maghanda=equip"},
            {"ceb", "Cebuano", "kanus-a=when;matag=every;sa=on;kung=if;gawas kung=unless;kung dili=else;balika=repeat;alang sa=for;hangtod=until;balik=return;aksyon=action;function=function;mando=command;menu=menu;ihatag=give;kuhaa=take;patya=kill;damage=damage;tambal=heal;teleport=teleport;spawn=spawn;itakda=set;dugang=add;kuhaon=remove;isulti=tell;ipahibalo=announce;paghimo=create;panagana=delete;luwas=save;karga=load;tawag=call;hulat=wait;cooldown=cooldown;lupad=fly;pakaon=feed;pagyelo=freeze;sugnod=ignite;mobuto=explode;gidili=ban;patid=kick;limpyo=clear;sirado=close;abli=open;hulog=drop;mahika=enchant;andam=equip"},
            {"jv", "Jawa", "nalika=when;saben=every;ing=on;yen=if;kajaba=unless;yen ora=else;baleni=repeat;kanggo=for;nganti=until;bali=return;tumindak=action;fungsi=function;prentah=command;menu=menu;menehi=give;njupuk=take;mateni=kill;ngrusak=damage;nambani=heal;teleport=teleport;spawn=spawn;nyetel=set;nambah=add;mbusak=remove;ngandhani=tell;ngumumake=announce;nggawe=create;mbusak=delete;nyimpen=save;ngunggah=load;nelpon=call;ngenteni=wait;cooldown=cooldown;mabur=fly;pakan=feed;beku=freeze;ngobong=ignite;njeblug=explode;nglarang=ban;nyepak=kick;resik=clear;nutup=close;mbukak=open;nyelehake=drop;nyihir=enchant;nyiapake=equip"},
            {"su", "Sunda", "nalika=when;unggal=every;dina=on;lamun=if;iwal=unless;upami henteu=else;ulangan=repeat;pikeun=for;nepi ka=until;balik=return;lampah=action;fungsi=function;paréntah=command;menu=menu;masihan=give;nyandak=take;maéhan=kill;ngarugikeun=damage;ngubaran=heal;teleport=teleport;spawn=spawn;nyetél=set;nambih=add;ngaleungitkeun=remove;nyarios=tell;ngumumkeun=announce;nyiptakeun=create;ngahapus=delete;nyimpen=save;ngamuat=load;nelepon=call;antosan=wait;cooling=cooldown;ngapung=fly;mapar=feed;beku=freeze;ngaduruk=ignite;ngabeledug=explode;ngalarang=ban;nyepak=kick;ngaberesihan=clear;nutup=close;muka=open;murag=drop;ngajimat=enchant;nyiapkeun=equip"},
            {"mkj", "Makhuwa", "ikata=when;waha=every;vanya=on;akhala=if;akhala thene=unless;makhala=else;phindha=repeat;wa=for;mpaka=until;wehiha=return;weherya=action;funsawo=function;nseketela=command;menu=menu;vaha=give;theka=take;uwaha=kill;wahana=damage;lamula=heal;teleport=teleport;spawn=spawn;weha=set;wahaniha=add;rusa=remove;waherya=tell;waruma=announce;thetiha=create;unanyiha=delete;suntha=save;lataha=load;wiihana=call;wiiraha=wait;mabiri=cooldown;urukha=fly;waana=feed;warima=freeze;wanna=ignite;waphula=explode;wukuma=ban;wattula=kick;wahehera=clear;wiira=close;wahula=open;woora=drop;wathantha=enchant;watthuka=equip"},
            {"haw", "ʻŌlelo Hawaiʻi", "ke=when;kēlā me kēia=every;ma luna=on;inā=if;koe=unless;a i ʻole=else;hōʻike hou=repeat;no=for;ā hiki=until;hoʻi=return;hana=action;hana=function;kauoha=command;menu=menu;hāʻawi=give;lawe=take;pepehi=kill;hōʻeha=damage;ola=heal;teleport=teleport;spawn=spawn;hoʻonoho=set;hoʻohui=add;wehe=remove;ʻōlelo=tell;hoʻolaha=announce;hana=create;holoi=delete;mālama=save;hoʻouka=load;kāhea=call;kali=wait;hoʻoluʻolu=cooldown;lele=fly;hānai=feed;paʻa hau=freeze;hoʻā=ignite;pahū=explode;pāpā=ban;kiʻi=kick;holoi=clear;pani=close;wehe=open;hāʻule=drop;kāpae=enchant;hoʻolako=equip"},
            // --- Indigenous Americas & minority European --------------------
            {"gn", "Guaraní", "jave=when;mayma=every;ari=on;jepé=if;pórke=unless;tero=else;jey=repeat;pe=for;peve=until;jevy=return;mba'e=action;funsión=function;ñe'ẽ=command;menú=menu;eme'ẽ=give;eja=take;juka=kill;mbyai=damage;monguera=heal;teleport=teleport;spawn=spawn;emoĩ=set;embojua=add;embogue=remove;erová=tell;marandu=announce;japo=create;jukapa=delete;ñongatu=save;ejupi=load;henói=call;eñha'ã=wait;ro'ỹ=cooldown;veve=fly;embojuru=feed;ro'ysã=freeze;tata=ignite;ñembopu=explode;mopu'ã=ban;echoka=kick;mopotĩ=clear;mbojuruja=close;pe'a=open;meméi=drop;paje=enchant;mohenda=equip"},
            {"qu", "Runasimi", "hayk'a=when;sapa=every;hawapi=on;spa=if;mana kanqachu=unless;hinaptin=else;kutichiy=repeat;paq=for;kama=until;kutichiy=return;ruway=action;funsiyun=function;kamachiy=command;menú=menu;quy=give;apay=take;wañuchiy=kill;dañuy=damage;hanpiy=heal;teleport=teleport;spawn=spawn;churaspa=set;yapay=add;hurquy=remove;willay=tell;willapay=announce;kamariy=create;pichay=delete;waqaychay=save;cargay=load;waqyay=call;suyay=wait;chiriyay=cooldown;phaway=fly;mikuchiy=feed;qasay=freeze;ninan=ignite;t'uqyay=explode;amachay=ban;haytay=kick;chuyanchay=clear;wichqay=close;kichay=open;wikch'uy=drop;layqay=enchant;waskhay=equip"},
            {"ay", "Aymar", "jichha=when;sapa=every;patxa=on;ukaña=if;jan ukaxa=unless;jan ukajja=else;yatiñakata=repeat;tha=for;kama=until;kutiyäna=return;luräwi=action;funsiyuna=function;kamachi=command;menú=menu;chura=give;katja=take;jiwaya=kill;dañu=damage;allstaya=heal;teleport=teleport;spawn=spawn;utuqta=set;yapxata=add;apxaru=remove;säña=tell;yatiyäwi=announce;lura=create;jarq'acha=delete;imxa=save;apaqa=load;jaysu=call;suyasiña=wait;thayapta=cooldown;phawa=fly;manq'aya=feed;ch'uwa=freeze;nayra=ignite;phatiya=explode;amulasiña=ban;jachu=kick;ch'umacha=clear;uwija=close;jist'ara=open;allani=drop;layqa=enchant;apatxa=equip"},
            {"mi", "Te Reo Māori", "ina=when;ia=every;ki runga=on;mehemea=if;ki te kore=unless;ki te kāhore=else;tōia=repeat;mō=for;tae noa=until;whakahoki=return;mahi=action;mahi=function;whakahau=command;menu=menu;hōmai=give;tangohia=take;patua=kill;tūkinotia=damage;ora=heal;teleport=teleport;spawn=spawn;whakatakoto=set;tāpiri=add;tango=remove;kōrero=tell;panui=announce;waihanga=create;mukua=delete;tiaki=save;uta=load;karanga=call;tatari=wait;whakamātao=cooldown;rere=fly;whāngai=feed;whakatio=freeze;tahuna=ignite;pahū=explode;rāhui=ban;whana=kick;horoi=clear;katia=close;whakatuwhera=open;maka=drop;makehe=enchant;whakaritea=equip"},
            {"to", "lea faka-Tonga", "ka=when;takatoa=every;ia=on;kapau=if;kapa'i=unless;kapau 'ikai=else;toe fai=repeat;ma'a=for;kia=until;foki=return;ngaue=action;fakatiní=function;fekau=command;menú=menu;ma'u=give;ave=take;tāmate=kill;lavea=damage;fakamo'ui=heal;teleport=teleport;spawn=spawn;fokotu'u=set;tanaki=add;ave atu=remove;tala=tell;fakahoko=announce;fa'u=create;fakamole=delete;tauhi=save;lolotonga=load;ui=call;tatali=wait;momoko=cooldown;puna=fly;fafanga=feed;'aisi=freeze;tā=ignite;fokotu'u=explode;tapui=ban;huhu=kick;fakama'a=clear;tapu=close;fakaava=open;tuku=drop;tokoni=enchant;teu=equip"},
            {"sm", "Gagana Sāmoa", "pe a=when;ta'itasi=every;i luga=on;afai=if;se'i vagana=unless;āfai e leai=else;toe fai=repeat;mo=for;se'ia=until;toe fo'i=return;gaioiga=action;galuega=function;poloaiga=command;menu=menu;tu'u atu=give;ave=take;fasi=kill;fa'amanu=damage;fofo=heal;teleport=teleport;spawn=spawn;fa'atu=set;faaopoopo=add;ave ese=remove;ta'u=tell;fa'asalalau=announce;faia=create;tape=delete;teu=save;utaina=load;valaau=call;faatali=wait;mālūlū=cooldown;lele=fly;fafaga=feed;'aisa=freeze;fa'amumu=ignite;pā=explode;fa'asa=ban;kiki=kick;fa'amama=clear;tapuni=close;tatala=open;tu'u=drop;fa'ataula=enchant;sauni=equip"},
            {"fy", "Frysk", "as=when;elke=every;op=on;as=if;útsein=unless;oars=else;werhelje=repeat;foar=for;oant=until;werom=return;aksje=action;funksje=function;kommando=command;menu=menu;jou=give;nim=take;deadzje=kill;skansearje=damage;genêze=heal;teleportearje=teleport;spawn=spawn;set=set;foegje ta=add;ferwiderje=remove;fertel=tell;oankundigje=announce;meitsje=create;wiskje=delete;bewarje=save;lade=load;roppe=call;wachtsje=wait;ôfkuolling=cooldown;fleane=fly;fiede=feed;befrieze=freeze;oanstekke=ignite;ploffe=explode;bannen=ban;skoppe=kick;leegje=clear;slute=close;iepenje=open;falle litte=drop;bitsjoene=enchant;útrisse=equip"},
            {"cy", "Cymraeg", "pan=when;bob=every;ar=on;os=if;oni bai=unless;fel arall=else;ailadrodd=repeat;ar gyfer=for;hyd=until;dychwelyd=return;gweithred=action;swyddogaeth=function;gorchymyn=command;dewislen=menu;rhoi=give;cymryd=take;lladd=kill;niweidio=damage;iachau=heal;telegludo=teleport;sbwrn=spawn;gosod=set;ychwanegu=add;tynnu=remove;dweud=tell;cyhoeddi=announce;creu=create;dileu=delete;cadw=save;llwytho=load;galw=call;aros=wait;oeri=cooldown;hedfan=fly;bwydo=feed;rhewi=freeze;cynnau=ignite;ffrwydro=explode;gwahardd=ban;cicio=kick;clirio=clear;cau=close;agor=open;ollwng=drop;hudo=enchant;arfogi=equip"},
            {"gd", "Gàidhlig", "nuair=when;gach=every;air=on;ma=if;a-mhàin=unless;air neo=else;ath-aithris=repeat;airson=for;gus=until;till=return;gnìomh=action;gnìomh=function;òrdugh=command;clàr-taice=menu;thoir=give;thoir=take;marbh=kill;mill=damage;slànaich=heal;teleport=teleport;spawn=spawn;suidhich=set;cuir ris=add;thoir air falbh=remove;innis=tell;gairm=announce;cruthaich=create;sguab às=delete;sàbhail=save;luchdaich=load;gairm=call;feitheamh=wait;fuarachadh=cooldown;itealaich=fly;biadhaich=feed;reòta=freeze;las=ignite;spreadh=explode;toirmisg=ban;breab=kick;glan=clear;dùin=close;fosgail=open;leig=drop;seun=enchant;armaich=equip"},
            {"ga", "Gaeilge", "nuair=when;gach=every;ar=on;má=if;mura=unless;seachas sin=else;athdhéan=repeat;do=for;go dtí=until;fill=return;gniomh=action;feidhm=function;ordú=command;roghchlár=menu;tabhair=give;glac=take;maraigh=kill;déan damáiste=damage;leigh=heal;teileaphortáil=teleport;spawn=spawn;leag=set;cuir le=add;bain=remove;inis=tell;fógair=announce;cruthaigh=create;scrios=delete;coinnigh=save;lódáil=load;glaoigh=call;fan=wait;fuarú=cooldown;eitil=fly;cothaigh=feed;reoigh=freeze;las=ignite;pléasc=explode;coisc=ban;ciceáil=kick;glan=clear;dún=close;oscail=open;lig=drop;asarlaíocht=enchant;fheistigh=equip"},
            // --- Constructed / Learning languages ---------------------------
            {"eo", "Esperanto", "kiam=when;ĉiu=every;sur=on;se=if;krom se=unless;alie=else;ripetu=repeat;por=for;ĝis=until;redonu=return;ago=action;funkcio=function;komando=command;menu=menu;donu=give;prenu=take;mortigu=kill;difektu=damage;sanku=heal;teleportu=teleport;aperigu=spawn;agu=set;aldomu=add;forigu=remove;diru=tell;anoncu=announce;kreu=create;forigu=delete;konservu=save;ŝarĝu=load;voku=call;atendu=wait;malvarmigo=cooldown;flugu=fly;nutru=feed;frostigu=freeze;ekbruligu=ignite;eksplodu=explode;malpermesu=ban;piedbatu=kick;malplenigu=clear;fermu=close;malfermu=open;faligu=drop;sorĉu=enchant;ekipu=equip"},
            {"la", "Latina", "quando=when;omnis=every;in=on;si=if;nisi=unless;aliter=else;repete=repeat;pro=for;usque=until;redde=return;actio=action;munus=function;imperium=command;menu=menu;da=give;cape=take;occide=kill;laede=damage;cura=heal;transporta=teleport;spawn=spawn;pone=set;adde=add;tolle=remove;dic=tell;annuntia=announce;crea=create;dele=delete;serva=save;onera=load;voca=call;expecta=wait;frigus=cooldown;vola=fly;pasee=feed;glacia=freeze;incende=ignite;explode=explode;prohibe=ban;calcitra=kick;purga=clear;claude=close;aperi=open;depone=drop;incanta=enchant;instrua=equip"},
            {"ilo", "Ilokano", "no=when;tunggal=every;iti=on;no=if;malaksid no=unless;no saan=else;uliten=repeat;para iti=for;agingga=until;agsubli=return;aramid=action;function=function;bilin=command;menu=menu;ited=give;alaen=take;papatayen=kill;dangran=damage;agas=heal;teleport=teleport;spawn=spawn;ipan=set;inayonan=add;ikkaten=remove;ibaga=tell;ipulong=announce;aramiden=create;ikkaten=delete;idal=save;i-load=load;awagan=call;agpaay=wait;cooldown=cooldown;agayam=fly;pakanen=feed;yelo=freeze;apuyan=ignite;agbettak=explode;iparit=ban;sitpa=kick;dalusen=clear;irikep=close;lukatan=open;ibain=drop;enkanto=enchant;agsagana=equip"},
            {"ht", "Kreyòl Ayisyen", "lè=when;chak=every;sou=on;si=if;sòf si=unless;sinon=else;repete=repeat;pou=for;jiska=until;retounen=return;aksyon=action;fonksyon=function;kòmand=command;meni=menu;bay=give;pran=take;touye=kill;blesse=damage;gerizon=heal;teleport=teleport;spawn=spawn;mete=set;ajoute=add;retire=remove;di=tell;anonse=announce;kreye=create;efase=delete;sove=save;chaje=load;rele=call;tann=wait;refwadisman=cooldown;vole=fly;ba manje=feed;jele=freeze;limen=ignite;eksploze=explode;entèdi=ban;choute=kick;netwaye=clear;fèmen=close;louvri=open;jete=drop;anchant=enchant;ekipe=equip"},
        };
        for (String[] row : data) {
            String code = row[0].toLowerCase();
            String name = row[1];
            LANGUAGES.put(code, name);
            BY_NATIVE.put(name.toLowerCase(), code);
            java.util.Map<String, String> map = new java.util.HashMap<>();
            String[] pairs = row[2].split(";");
            for (String pair : pairs) {
                int eq = pair.indexOf('=');
                if (eq > 0) {
                    String foreign = pair.substring(0, eq).trim().toLowerCase();
                    String canonical = pair.substring(eq + 1).trim();
                    // Keep the first meaning: header words ("when", "if", ...)
                    // are listed first in every row and must win any collision.
                    map.putIfAbsent(foreign, canonical);
                }
            }
            TABLES.put(code, map);
        }
    }
}
